/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string = string> extends Record<string, unknown> {
      StaticRoutes: `/` | `/(auth)` | `/(auth)/` | `/(auth)/contacts` | `/(auth)/phone` | `/(auth)/profile-setup` | `/(auth)/verify` | `/(main)` | `/(main)/circles` | `/(main)/circles/` | `/(main)/dms` | `/(main)/dms/` | `/(main)/moments` | `/(main)/moments/` | `/(main)/moments/create` | `/(main)/profile` | `/(main)/profile/` | `/_sitemap` | `/circles` | `/circles/` | `/contacts` | `/dms` | `/dms/` | `/moments` | `/moments/` | `/moments/create` | `/phone` | `/profile` | `/profile-setup` | `/profile/` | `/verify`;
      DynamicRoutes: `/(main)/circles/${Router.SingleRoutePart<T>}` | `/(main)/circles/${Router.SingleRoutePart<T>}/bet/${Router.SingleRoutePart<T>}` | `/(main)/circles/${Router.SingleRoutePart<T>}/bet/create` | `/(main)/circles/${Router.SingleRoutePart<T>}/bets` | `/(main)/circles/${Router.SingleRoutePart<T>}/expense/create` | `/(main)/circles/${Router.SingleRoutePart<T>}/expenses` | `/(main)/circles/${Router.SingleRoutePart<T>}/lottery` | `/(main)/circles/${Router.SingleRoutePart<T>}/lottery/create` | `/(main)/circles/${Router.SingleRoutePart<T>}/private-room/${Router.SingleRoutePart<T>}` | `/(main)/circles/${Router.SingleRoutePart<T>}/private-room/create` | `/(main)/circles/${Router.SingleRoutePart<T>}/private-room/join` | `/(main)/circles/${Router.SingleRoutePart<T>}/private-rooms` | `/(main)/circles/${Router.SingleRoutePart<T>}/room` | `/(main)/moments/${Router.SingleRoutePart<T>}` | `/circles/${Router.SingleRoutePart<T>}` | `/circles/${Router.SingleRoutePart<T>}/bet/${Router.SingleRoutePart<T>}` | `/circles/${Router.SingleRoutePart<T>}/bet/create` | `/circles/${Router.SingleRoutePart<T>}/bets` | `/circles/${Router.SingleRoutePart<T>}/expense/create` | `/circles/${Router.SingleRoutePart<T>}/expenses` | `/circles/${Router.SingleRoutePart<T>}/lottery` | `/circles/${Router.SingleRoutePart<T>}/lottery/create` | `/circles/${Router.SingleRoutePart<T>}/private-room/${Router.SingleRoutePart<T>}` | `/circles/${Router.SingleRoutePart<T>}/private-room/create` | `/circles/${Router.SingleRoutePart<T>}/private-room/join` | `/circles/${Router.SingleRoutePart<T>}/private-rooms` | `/circles/${Router.SingleRoutePart<T>}/room` | `/moments/${Router.SingleRoutePart<T>}`;
      DynamicRouteTemplate: `/(main)/circles/[id]` | `/(main)/circles/[id]/bet/[betId]` | `/(main)/circles/[id]/bet/create` | `/(main)/circles/[id]/bets` | `/(main)/circles/[id]/expense/create` | `/(main)/circles/[id]/expenses` | `/(main)/circles/[id]/lottery` | `/(main)/circles/[id]/lottery/create` | `/(main)/circles/[id]/private-room/[roomId]` | `/(main)/circles/[id]/private-room/create` | `/(main)/circles/[id]/private-room/join` | `/(main)/circles/[id]/private-rooms` | `/(main)/circles/[id]/room` | `/(main)/moments/[id]` | `/circles/[id]` | `/circles/[id]/bet/[betId]` | `/circles/[id]/bet/create` | `/circles/[id]/bets` | `/circles/[id]/expense/create` | `/circles/[id]/expenses` | `/circles/[id]/lottery` | `/circles/[id]/lottery/create` | `/circles/[id]/private-room/[roomId]` | `/circles/[id]/private-room/create` | `/circles/[id]/private-room/join` | `/circles/[id]/private-rooms` | `/circles/[id]/room` | `/moments/[id]`;
    }
  }
}
